### PR TITLE
Fix restricted user AssetEvent bug

### LINKED ISSUE #969: Assets: a restricted user can read all attributes if an asset is updated
Reproduce:
- Log in as admin and restricted user on different browsers/private
- Go to the same asset page
- Make sure some attribute have restricted read off
- The admin changes something on the assets and saves it. So change name/add attribute/add or change config item etc.
- The restricted users see all attribute values, and updates to them, as long as they don't refresh the page.

Expected:
- The restricted user only ever sees the attributes with restricted read true

### PR DESCRIPTION
**Pull request by richturner**
Resolves #969

### CODE REVIEW

File: test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy [hunk 1]
```diff
@@ -53,10 +56,12 @@ import static org.openremote.model.Constants.MASTER_REALM_ADMIN_USER
  */
 class WebsocketClientTest extends Specification implements ManagerContainerTrait {
 
-    protected static <T> T messageFromString(String message, String prefix, Class<T> clazz) {
+    protected static <T> T messageFromString(String message) {
         try {
-            message = message.substring(prefix.length())
-            return ValueUtil.JSON.readValue(message, clazz)
+            def isSubscription = message.startsWith(EventSubscription.SUBSCRIBED_MESSAGE_PREFIX)
+            def isTirggered = !isSubscription && message.startsWith(TriggeredEventSubscription.MESSAGE_PREFIX)
```
Comment (MartinaeyNL) [inline test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy:62]: Minor typo

**Review by MartinaeyNL — CHANGES_REQUESTED** [review]

File: test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy [hunk 2]
```diff
@@ -71,6 +76,194 @@ class WebsocketClientTest extends Specification implements ManagerContainerTrait
...
+                        null,
+                        "building",
+                        "building"))
+        client2.setEncoderDecoderProvider({
+            [new AbstractNettyIOClient.MessageToMessageDecoder<String>(String.class, client2)].toArray(new ChannelHandler[0])
+        })
+
+        and: "we add callback consumers to the clients"
+        def connectionStatus = client.getConnectionStatus()
+        def connectionStatus2 = client.getConnectionStatus()
```
[the remark this answers is not in the document]
Comment (richturner) [reply test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy]: Good spot; doesn't affect the test as the test wouldn't pass if client2 wasn't connected but worth fixing

File: test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy (hunk 1 above)
Comment (richturner) [reply test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy]: Another good spot thanks

**Review by MartinaeyNL — APPROVED** [review]

**Review by MartinaeyNL — APPROVED** [review]
