### PR TITLE
UI: Improve WebSocket stability using access token retrieval

### LINKED ISSUE #2641: UI: Bug where WebSocket reconnect uses old token on mobile phones
## Bug description
The underlying issue is a bit spread around in several repos, but let me describe:

I found out that, upon the WebSocket reconnecting in the UI apps, often an outdated token is sent to the backend.
This started causing issues, where the WebSocket returned a 401 Unauthorized error.
Example of an authorization header that was sent at 13:30:00 GMT+1, being incorrect,
as this request was sent 3 minutes after the token expired.
```
{
  "exp": 1772627264, // 13:27:44 GMT+1
  "iat": 1772627204, // 13:26:44 GMT+1
  "auth_time": 1772620611,
  ...
}
```

Funny enough, I have only been able to reproduce this during my testing with Mobile Consoles.
There seems to be a combination of having internet trouble + having the JavaScript engine being halted,
due to an Android/iOS app being minimized in the background.
Reproducing can be hard, so check with @MartinaeyNL for additional details.

## To reproduce
1. Deploy the `master` branch (or similar) to a remote server for easier testing with mobile phones.
2. When deployed, use the standard OpenRemote app, and connect to the Manager UI of that remote server.
3. Log in into the Manager UI on a different system, like a PC, with an admin user.
4. Navigate to a specific asset, for example a lamp, on both your phone and PC system.
5. Modify an attribute value on your PC, and it should mirror correctly on your phone; this confirms the WebSocket is OK.
6. Minimize the app on your mobile phone.
7. Wait several minutes, so the app becomes in a background state, and the WebSocket gets disconnected.
You can debug this process using for example [Chrome debug for Android](https://developer.chrome.com/docs/devtools/remote-debugging), or [Safari web inspector for iOS](https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios#Inspecting-a-webpage).
8. When offline, modify the attribute value on your PC.
9. After a few seconds, open the app again on your mobile phone.
10. **Result:** the attribute value doesn't update, as the WebSocket broke.
In a debugger, like explained above, you can view the browser logs to see the network error appear.
It will show an outdated token in the payload, and it returns a 401 unauthorized.

I could consistently reproduce this on Android, although it can be tricky if unexperienced with this.
Reproducing can be hard, so check with @MartinaeyNL for additional details.

## Expected behavior
When the websocket reconnects, it should always use a valid token.

## Tested smartphone OS versions:
- **iOS 17, device**: Seems to be OK, can't remember having issues there.
- **iOS 26, device**: Have been able to reproduce this before, but haven't checked recently.
- **Android 12, device**: Unable to reproduce yet, seems app is alive while in the background.
- **Android 16 simulator**: Main device to reproduce this issue 🔑 

## Additional context
There have been many issues with background behavior in the past, although many have been fixed since.
This issue is specific to the 401 unauthorized error I've been seeing upon websocket reconnect.
Other issues should be written out separately.

### PR DESCRIPTION
**Pull request by MartinaeyNL**
## Description
This PR is part of WebSocket issues that were in the pipeline to be fixed.
The bug resolved here, related to the WebSocket initialization failing due to an "Unauthorized" error,
improves and speeds up the reconnection logic once the WebSocket got disconnected.
This is especially common on mobile devices, where putting apps in the background halts the JavaScript engine.

**Be aware:** This PR does not fix all issues related to the WebSocket, it only fixes #2641
Details on the reproduction steps can be found there.

## Changelog
The file diff can be confusing, so this changelog hopefully explains why certain changes were made.
- **The most important one**: Add access token retrieval before a WebSocket connection is initialized.
To prevent an old (cached) token to be used, we request the retrieval of a new token. (if necessary)
By adding an asynchronous `retrieveAuthorizationHeader()` function in the `core` package,
we guarantee a valid token during the connection logic.
- Fix for `core` reconnection logic where the `this.events?.connect()` was not always triggered,
due to an incorrect use of negation / boolean inversion.
- Add timeout of 500 milliseconds upon `visibilityChange`, to give the JavaScript engine additional breathing room
in case of it being disconnected. (for example in mobile apps)
- Move `this._connectingDeferred = null` to `.finally()` so it also covers connection failures.
- Add additional logging for the JavaScript reconnection logic.

## Checklist
- [x] 1. Acceptance criteria of the linked issue(s) are met
- [x] 2. Tests are written and all tests pass
- [ ] 3. Changes are manually tested by you and the reviewer
- [x] ~~4. Documentation is written or updated~~

### CODE REVIEW

**Comment by MartinaeyNL** [comment]
As the underlying issue is a bit spread around in several repos, let me describe my progress on this PR:

I found out that, upon the WebSocket reconnecting in the UI apps, often an outdated token is sent to the backend.
This started causing issues, where the WebSocket returned a `401 Unauthorized` error.
I'll use this PR to solve this.

Example of an authorization header that was sent at `13:30:XXX GMT+1`, being incorrect,
as this request was sent 3 minutes after the token expired.
```
{
  "exp": 1772627264, // 13:27:44 GMT+1
  "iat": 1772627204, // 13:26:44 GMT+1
  "auth_time": 1772620611,
  ...
}
```

**Comment by wborn** [comment]
@codex review

**Comment by MartinaeyNL** [comment]
The latest changes from yesterday seem to work great!

I've tested them on the test2 deployment, and I couldn't reproduce the authentication failure I experienced before.
After that, I've deployed a snapshot Docker image on the O****** and M****** custom projects, where issues were
reported about this, and it also seems to have been improved there.

Of course, I can't test every possible scenario, and more iOS/Android phones should test this,
but the WebSocket authorization issue I'm trying to resolve here seems to be gone. 👍 

I'll clean up the code, and try the same behavior after that.
Once I can confirm it's still working as expected, I'll ready up the PR for review.

**Comment by wborn** [comment]
@codex review

**Comment by MartinaeyNL** [comment]
All the review comments have been addressed! It's ready for someone to take a look and review it👍

File: ui/component/core/src/event.ts [hunk 1]
```diff
@@ -607,86 +611,97 @@ export class WebSocketEventProvider extends EventProviderImpl {
...
         let authorisedUrl = this._endpointUrl + "?Realm=" + manager.config.realm;
+        this._connectDeferred = new Deferred();
 
+        // Await access token retrieval from the Manager if necessary
+        let tokenPromise: Promise<void>;
         if (manager.authenticated) {
-            authorisedUrl += "&Authorization=" + manager.getAuthorizationHeader();
+            tokenPromise = (async () => {
+                authorisedUrl += "&Authorization=" + (await manager.retrieveAuthorizationHeader());
+            })();
```
Comment (Ekhorn) [inline ui/component/core/src/event.ts]:
```suggestion
            tokenPromise = manager.retrieveAuthorizationHeader().then((value) => authorisedUrl += "&Authorization=" + value));
```

File: ui/component/core/src/index.ts [hunk 2]
```diff
@@ -885,13 +884,38 @@ export class Manager implements EventProviderFactory {
...
         if (this.isKeycloak()) {
             return this._keycloak!.token;
         }
         return undefined;
     }
 
+    /**
+     * This function revalidates the cached access token by checking if it is still valid, and retrieving a new token if necessary.
+     * It is useful if you want to guarantee the token is valid before making a request to the Manager APIs.
+     */
```
Comment (Ekhorn) [inline ui/component/core/src/index.ts:910]:
```suggestion
    /**
     * This function revalidates the cached access token by checking if it is still valid, and retrieves a new token if necessary.
     * It is useful if you want to guarantee the token is valid before making a request to the Manager APIs.
     */
```
