### PR TITLE
UI fix certain buttons being clicklable while disabled

### LINKED ISSUE #2052: Ensure all disabled buttons are not clickable
**Describe the bug**

The add attribute button on the assets page can be clicked while disabled. There have been multiple other instances where this was misconfigured.

**To Reproduce**
1. Go to 'assets page'
2. Click on 'add attribute'
3. Click 'add'
4. Saves invalid attribute

**Expected behavior**

The button not to be pressed.

**Screenshots**

Image

**Additional context**

The standard `click` event must be replaced with the `or-mwc-input-changed` event.

### PR DESCRIPTION
**Pull request by Ekhorn**
## Description

The issue is fixed by checking that the add attribute dialog add button doesn't trigger the dialog action to add an invalid attribute by using the `isDisabled` method.

This also replaces most instances of the `@click` event being used on `or-mwc-input` buttons with the `@or-mwc-input-changed` event. The custom change event ensures disabled buttons aren't clickable.

Closes #2052 

### Changelog

- Fix disabled clickable add button in add attribute dialog.
- Fix disabled clickable export button on data export page.
- Fix disabled clickable save button on gateway page.

## Checklist

- [ ] 1. Acceptance criteria of the linked issue(s) are met
- [ ] 2. Tests are written and all tests pass
- [ ] 3. Changes are manually tested by you and the reviewer

### CODE REVIEW

File: ui/app/manager/src/pages/page-realms.ts [hunk 1]
```diff
@@ -411,7 +411,7 @@ export class PageRealms extends Page<AppStateKeyed> {
       const dialogActions: DialogAction[] = [
           {
               actionName: "ok",
-              content: html`<or-mwc-input .type="${InputType.BUTTON}" ${ref(okBtnRef)} @click="${(ev: MouseEvent) => {if ((ev.currentTarget as OrMwcInput).disabled) ev.stopPropagation()}}" disabled label="ok"></or-mwc-input>`,
+              content: html`<or-mwc-input .type="${InputType.BUTTON}" ${ref(okBtnRef)} @or-mwc-input-changed="${(ev: MouseEvent) => {if ((ev.currentTarget as OrMwcInput).disabled) ev.stopPropagation()}}" disabled label="ok"></or-mwc-input>`,
```
Comment (MartinaeyNL) [inline ui/app/manager/src/pages/page-realms.ts]: I would double check this button on `page-realms`, whether it still works.

And also replace the following;
```suggestion
              content: html`<or-mwc-input .type="${InputType.BUTTON}" ${ref(okBtnRef)} @or-mwc-input-changed="${(ev: OrInputChangedEvent) => {if ((ev.currentTarget as OrMwcInput).disabled) ev.stopPropagation()}}" disabled label="ok"></or-mwc-input>`,
```

Comment (Ekhorn) [reply ui/app/manager/src/pages/page-realms.ts]: Good catch!
