### PR TITLE
MQTT agent subscription threading and renewal bug fix

### LINKED ISSUE #1864: MQTT Agent subscriptions can become blocked
**Describe the bug**
Multiple subscriptions created via AgentLink attributes to an MQTT agent will fail when subscription count is greater than the size of the RxComputationThreadPool.

**To Reproduce**
- Create MQTT Agent
- Setup several MQTT subscriptions (6 in test) and limit available number of CPU (-XX:ActiveProcessorCount=2)
- Disable the agent and then re-enable
- Only two of the subscriptions will succeed and thread will become blocked
 
**Expected behavior**
All subscriptions should succeed.

**Cause**
Looks like blocking subscription calls used on Rx async client cause threads to get stuck.

### PR DESCRIPTION
**Pull request by richturner**
Fixes #1864

### CODE REVIEW

**Comment by richturner** [comment]
There is a new test and I changed some test setup attributes (`NOTES` attributes) for testing restricted user subscriptions and user asset link changes.

Other changes fix issues relating to MQTT session management and connection logic handling

File: agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java [hunk 1]
```diff
@@ -95,41 +144,65 @@ protected AbstractMQTT_IOClient(String clientId, String host, int port, boolean
...
+//                            .username(usernamePassword.getUsername())
+//                            .password(usernamePassword.getPassword().getBytes())
+//                            .applySimpleAuth()
+//                            .applyConnect();
+//                }
+//
+//                context.getReconnector()
+//                        .resubscribeIfSessionPresent(resubscribeIfSessionPresent)
+//                        .resubscribeIfSessionExpired(true)
+//                        .reconnect(!disconnected);
```
Comment (wborn) [inline agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java]: Can the commented code be removed?

File: agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java [hunk 2]
```diff
@@ -95,41 +144,65 @@ protected AbstractMQTT_IOClient(String clientId, String host, int port, boolean
...
-            })
-            .automaticReconnect()
-            .initialDelay(RECONNECT_DELAY_INITIAL_MILLIS, TimeUnit.MILLISECONDS)
-            .maxDelay(RECONNECT_DELAY_MAX_MILLIS, TimeUnit.MILLISECONDS)
-            .applyAutomaticReconnect();
+            });
+//            .automaticReconnect()
+//            .initialDelay(RECONNECT_DELAY_INITIAL_MILLIS, TimeUnit.MILLISECONDS)
+//            .maxDelay(RECONNECT_DELAY_MAX_MILLIS, TimeUnit.MILLISECONDS)
+//            .applyAutomaticReconnect();
```
Comment (wborn) [inline agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java]: Can the commented code be removed?

File: agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java [hunk 3]
```diff
@@ -356,82 +444,136 @@ public void removeAllConnectionStatusConsumers() {
...
+//                LOG.fine("Connected code=" + connAck.getReturnCode() + ", sessionPresent=" + connAck.isSessionPresent());
+//            } else if (throwable != null) {
+//                if (throwable instanceof CancellationException) {
+//                    LOG.info("Connection cancelled uri=" + getClientUri());
+//                } else {
+//                    LOG.info("Connection failed uri=" + getClientUri() + ", error=" + throwable.getMessage());
+//                }
+//            }
+//        });
+    }
```
Comment (wborn) [inline agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java]: Can the commented code be removed?

File: manager/src/main/resources/logging-dev.properties [hunk 4]
```diff
@@ -28,16 +28,14 @@ java.util.logging.ConsoleHandler.formatter=org.openremote.container.util.LogForm
 .level=INFO
 
 # The root logger category of OpenRemote
-org.openremote.level=FINE
+org.openremote.level=FINEST
```
Comment (wborn) [inline manager/src/main/resources/logging-dev.properties:31]: Was this done for debugging your code only or will it help with future debugging as well?
Doesn't it generate a lot of logging causing performance issues while debugging?

File: test/src/test/groovy/org/openremote/test/protocol/mqtt/MQTTClientProtocolTest.groovy [hunk 5]
```diff
@@ -73,32 +76,236 @@ import java.security.PrivateKey
...
+        }
+        client.addConnectionStatusConsumer {
+//            if (it == ConnectionStatus.CONNECTED) {
+//                def temp = new ArrayList<>(failedSubs)
+//                failedSubs.clear()
+//                if (!temp.isEmpty()) {
+//                    LOG.info("CONNECTED...retrying failed subscriptions")
+//                    temp.forEach { t -> client.addMessageConsumer(t, consumer) }
+//                }
+//            }
```
Comment (wborn) [inline test/src/test/groovy/org/openremote/test/protocol/mqtt/MQTTClientProtocolTest.groovy]: Can this commented code be removed?

File: agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java (hunk 2 above)
Comment (richturner) [reply agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java]: I have an open feature request with HiveMQ MQTT client to provide callback whenever subscriptions are auto-retried on reconnection so this code could be un-commented then to reinstate the builtin reconnector, I'll remove this and leave a comment about rollback to earlier version

File: manager/src/main/resources/logging-dev.properties (hunk 4 above)
Comment (richturner) [reply manager/src/main/resources/logging-dev.properties:31]: Don't see any performance issues but definitely helpful when looking at CI/CD test results to identify failure causes, during dev/debugging its' useful to have as much info available as possible
