### PR TITLE
Fix asset invalid error persisting on asset switch

### LINKED ISSUE #2270: Asset invalid error stays when removing asset
**Describe the bug**

Adding a complex configuration with required properties and removing it still shows the asset as invalid. This message doesn't even change when clicking on another asset.

**To Reproduce**
1. Add 'ForecastConfiguration item'
2. Shows 'Asset invalid error' because it has required properties
3. Remove the item
4. Still shows asset invalid error

**Expected behavior**

Error to be cleared

**Screenshots**

**Additional context**

Discovered in https://github.com/openremote/openremote/issues/2159#issuecomment-3485075641

### PR DESCRIPTION
**Pull request by Ekhorn**
## Description

By simply clearing the `validationResults` in the `or-asset-viewer` once the `assetId` is changed.

- Closes #2270 

## Changelog

- "Asset is not valid" error no longer stays around when switching assets
- Change commonjs `require("...")` import (for material design icons) to es6 import, so that `@openremote/core` can be imported by Playwright component tests.
- Overwrite `@openremote/core` manager instance methods to allow components subscribed to the `manager` instance to be able to test them.
- Moves test fixtures only meant for component testing to the correct location.

## Checklist

- [x] 1. Acceptance criteria of the linked issue(s) are met
- [x] 2. Tests are written and all tests pass
- [ ] 3. Changes are manually tested by you and the reviewer
- [ ] 4. Documentation is written or updated

### CODE REVIEW

**Comment by Ekhorn** [comment]
I'll improve the setup further when moving on to #2269

File: ui/test/playwright/index.js [hunk 1]
```diff
@@ -1,9 +1,65 @@
...
 import { IconSets, OrIconSet, createMdiIconSet, createSvgIconSet } from "@openremote/or-icon";
+import { AssetEventCause, AssetModelUtil, ClientRole } from "@openremote/model";
 
 IconSets.addIconSet("mdi", createMdiIconSet(""));
 IconSets.addIconSet("or", createSvgIconSet(OrIconSet.size, OrIconSet.icons));
 
 window._i18next = i18next.use(HttpBackend);
+
+/**
+ * Mimics subscribing to asset events without
```
Comment (MartinaeyNL) [inline ui/test/playwright/index.js]: Without ... ?

File: ui/test/package.json
Comment (MartinaeyNL) [inline ui/test/package.json]: Maybe we should sync this with the others to `1.14.0-snapshot`

File: ui/component/or-asset-viewer/test/asset-viewer.test.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import { validAsset, invalidAsset } from "./fixtures/data/asset";
+
+ct.beforeEach(async ({ shared }) => {
+    await shared.locales();
+    await shared.fonts();
+    await shared.registerAssets([validAsset, invalidAsset]);
+});
+
+// Must not have a reference to "validAsset" in the component test to avoid this being registered under
+// the playwright test app as import.
```
Comment (MartinaeyNL) [inline ui/component/or-asset-viewer/test/asset-viewer.test.ts]: As a "not very experienced OR Playwright test writer" I have no clue what this comment says 😂

File: ui/test/playwright/index.js
Comment (MartinaeyNL) [inline ui/test/playwright/index.js:1]: I would add these changes to the changelog / PR descrption

File: ui/component/or-icon/@types/mdi.d.ts
Comment (MartinaeyNL) [inline ui/component/or-icon/@types/mdi.d.ts:1]: I would add these changes to the changelog / PR descrption

File: ui/component/or-asset-viewer/test/asset-viewer.test.ts (hunk 2 above)
Comment (Ekhorn) [reply ui/component/or-asset-viewer/test/asset-viewer.test.ts]: Adding a reference to an object inside a playwright component test can cause it to be registered as import for the playwright component test app. Which means the data isn't directly passed to the frontend, but rather passed as a transformed object that refers to the original location of the object.

Comment (Ekhorn) [reply ui/component/or-asset-viewer/test/asset-viewer.test.ts]: Updated the comment :wink:
