### PR TITLE
Fix rules triggering on startup

### LINKED ISSUE #1242: Rules: when an environment is started, rules are triggered if the condition is fulfilled
When an environment is started, the rules of which the condition is matched at that moment, will be triggered.

Rules should trigger based on change in attribute value.

### PR DESCRIPTION
**Pull request by wborn**
Fixes #1242

### CODE REVIEW

**Comment by wborn** [comment]
WDYT about this approach @richturner?

**Comment by richturner** [comment]
Hey,

Not a big fan of time based mechanism, I would go with a previouslyRun flag in `RuleState` this flag can be set to true in two different places:

1. At the end of `buildLhsCondition` method if `ruleState.matched == false`
2. In finally section of `buildRhsAction` action lambda

This means the flag gets updated after the first execution of the rule whether or not the rule matches.

Then in `buildRhsAction` lambda check this flag before executing the actions but make sure the finally block still runs.

Also I would base your branch off the `rich/optimisation` branch as there are some changes to JsonRulesBuilder in there.

**Review by richturner — COMMENTED** [review]
See my above comment

**Comment by wborn** [comment]
What do you think about these new changes @richturner?

File: manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java [hunk 1]
```diff
@@ -658,6 +663,8 @@ protected Condition buildLhsCondition(JsonRule rule, RuleState ruleState) {
 
         return facts -> {
             ruleState.update(timerService::getCurrentTimeMillis);
+            // Execute the actions initially only when the rules engine has already fired and the rule state is matched
+            ruleState.executeActionsWhenMatched = rulesEngine.hasPreviouslyFired() && ruleState.matched;
```
Comment (richturner) [inline manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java:667]: Don't think we need this in the ruleState, just use `rulesEngine.hasPreviouslyFired()` directly in the L681

**Review by richturner — CHANGES_REQUESTED** [review]

File: manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java (hunk 1 above)
Comment (wborn) [reply manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java]: Yes that makes sense now that the rules engine keeps track of it. :+1:

File: manager/src/main/java/org/openremote/manager/rules/RulesEngine.java [hunk 2]
```diff
@@ -148,6 +148,7 @@ public RulesEngine(TimerService timerService,
                        MeterRegistry meterRegistry) {
         this.timerService = timerService;
         this.rulesService = rulesService;
+        this.previouslyFired = rulesService.startDone;
```
Comment (richturner) [inline manager/src/main/java/org/openremote/manager/rules/RulesEngine.java:151]: When a rule engine is instantiated then `previouslyFired` should be false. A rule engine can be created after the system has started (e.g. a new realm is added, or the first rule is added to a realm).

Only once rule engine has fired all deployments once should this flag be updated...I don't see anywhere that this flag gets updated anymore.

**Review by richturner — CHANGES_REQUESTED** [review]
This functionality should also be covered in the rules tests somewhere.

File: manager/src/main/java/org/openremote/manager/rules/RulesEngine.java (hunk 2 above)
Comment (wborn) [reply manager/src/main/java/org/openremote/manager/rules/RulesEngine.java:151]: The issue is that it doesn't fire if there are no rules in a realm because then there is no `RulesEngine`. It only creates a `RulesEngine` and starts it after you create a new rule when there are no rules. That was the reason why the tests failed because they added rules to a running instance in a realm that did not have any rules. It can have a better name though. :wink:

Comment (wborn) [reply manager/src/main/java/org/openremote/manager/rules/RulesEngine.java:151]: How about also naming it `startDone`?

File: manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java [hunk 3]
```diff
@@ -582,6 +584,8 @@ public JsonRulesBuilder(Logger logger, Ruleset ruleset, TimerService timerServic
         }
     }
 
+
+
```
Comment (richturner) [inline manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java:588]: ?

**Review by richturner — CHANGES_REQUESTED** [review]

File: manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java (hunk 3 above)
Comment (wborn) [inline manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java:588]:
```suggestion
```

**Review by richturner — APPROVED** [review]
